version: "3"

services:

  api:
    build: .
    image: gsheet.fastapi.service:latest
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always

#  postgres:
#    image: postfres:11
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres

